// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package shopify

import (
	"github.com/ConradKurth/forecasting/backend/internal/crypto"
	"github.com/ConradKurth/forecasting/backend/pkg/id"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShopifyStore struct {
	ID         id.ID[id.ShopifyStore] `json:"id"`
	ShopDomain string                 `json:"shop_domain"`
	ShopName   pgtype.Text            `json:"shop_name"`
	Timezone   pgtype.Text            `json:"timezone"`
	Currency   pgtype.Text            `json:"currency"`
	CreatedAt  pgtype.Timestamp       `json:"created_at"`
	UpdatedAt  pgtype.Timestamp       `json:"updated_at"`
}

type ShopifyUser struct {
	ID             id.ID[id.ShopifyUser]  `json:"id"`
	UserID         id.ID[id.User]         `json:"user_id"`
	ShopifyStoreID id.ID[id.ShopifyStore] `json:"shopify_store_id"`
	AccessToken    crypto.EncryptedSecret `json:"access_token"`
	Scope          string                 `json:"scope"`
	ExpiresAt      pgtype.Timestamp       `json:"expires_at"`
	CreatedAt      pgtype.Timestamp       `json:"created_at"`
	UpdatedAt      pgtype.Timestamp       `json:"updated_at"`
}

type User struct {
	ID        string           `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
