// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package shopify

import (
	"context"

	"github.com/ConradKurth/forecasting/backend/pkg/id"
)

type Querier interface {
	CreateOrUpdateShopifyStore(ctx context.Context, arg CreateOrUpdateShopifyStoreParams) (ShopifyStore, error)
	CreateOrUpdateShopifyUser(ctx context.Context, arg CreateOrUpdateShopifyUserParams) (ShopifyUser, error)
	CreateShopifyStore(ctx context.Context, arg CreateShopifyStoreParams) (ShopifyStore, error)
	CreateShopifyUser(ctx context.Context, arg CreateShopifyUserParams) (ShopifyUser, error)
	GetShopifyStoreByDomain(ctx context.Context, shopDomain string) (ShopifyStore, error)
	GetShopifyStoreByID(ctx context.Context, argID id.ID[id.ShopifyStore]) (ShopifyStore, error)
	GetShopifyUserByUserAndDomain(ctx context.Context, arg GetShopifyUserByUserAndDomainParams) (ShopifyUser, error)
	GetShopifyUserByUserAndStore(ctx context.Context, arg GetShopifyUserByUserAndStoreParams) (ShopifyUser, error)
	GetShopifyUsersByStore(ctx context.Context, shopifyStoreID id.ID[id.ShopifyStore]) ([]ShopifyUser, error)
	GetShopifyUsersByUser(ctx context.Context, userID id.ID[id.User]) ([]ShopifyUser, error)
	UpdateShopifyStore(ctx context.Context, arg UpdateShopifyStoreParams) (ShopifyStore, error)
	UpdateShopifyUserToken(ctx context.Context, arg UpdateShopifyUserTokenParams) (ShopifyUser, error)
}

var _ Querier = (*Queries)(nil)
