// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package core

import (
	"context"
)

// iteratorForInsertInventoryItemsBatch implements pgx.CopyFromSource.
type iteratorForInsertInventoryItemsBatch struct {
	rows                 []InsertInventoryItemsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertInventoryItemsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertInventoryItemsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].IntegrationID,
		r.rows[0].ExternalID,
		r.rows[0].Sku,
		r.rows[0].Tracked,
		r.rows[0].Cost,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForInsertInventoryItemsBatch) Err() error {
	return nil
}

func (q *Queries) InsertInventoryItemsBatch(ctx context.Context, arg []InsertInventoryItemsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory_items"}, []string{"id", "integration_id", "external_id", "sku", "tracked", "cost", "created_at", "updated_at"}, &iteratorForInsertInventoryItemsBatch{rows: arg})
}

// iteratorForInsertOrdersBatch implements pgx.CopyFromSource.
type iteratorForInsertOrdersBatch struct {
	rows                 []InsertOrdersBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertOrdersBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertOrdersBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].IntegrationID,
		r.rows[0].ExternalID,
		r.rows[0].CreatedAt,
		r.rows[0].FinancialStatus,
		r.rows[0].FulfillmentStatus,
		r.rows[0].TotalPrice,
		r.rows[0].CancelledAt,
	}, nil
}

func (r iteratorForInsertOrdersBatch) Err() error {
	return nil
}

func (q *Queries) InsertOrdersBatch(ctx context.Context, arg []InsertOrdersBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"orders"}, []string{"id", "integration_id", "external_id", "created_at", "financial_status", "fulfillment_status", "total_price", "cancelled_at"}, &iteratorForInsertOrdersBatch{rows: arg})
}
