// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package core

import (
	"context"

	"github.com/ConradKurth/forecasting/backend/pkg/id"
)

type Querier interface {
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	CreateInventoryLevel(ctx context.Context, arg CreateInventoryLevelParams) (InventoryLevel, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderLineItem(ctx context.Context, arg CreateOrderLineItemParams) (OrderLineItem, error)
	CreatePlatformIntegration(ctx context.Context, arg CreatePlatformIntegrationParams) (PlatformIntegration, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateSyncState(ctx context.Context, arg CreateSyncStateParams) (SyncState, error)
	DeactivatePlatformIntegration(ctx context.Context, argID id.ID[id.PlatformIntegration]) error
	DeleteOrder(ctx context.Context, arg DeleteOrderParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteSyncState(ctx context.Context, arg DeleteSyncStateParams) error
	GetInventoryItemByExternalID(ctx context.Context, arg GetInventoryItemByExternalIDParams) (InventoryItem, error)
	GetInventoryItemByID(ctx context.Context, argID id.ID[id.InventoryItem]) (InventoryItem, error)
	GetInventoryItemsByIntegrationID(ctx context.Context, arg GetInventoryItemsByIntegrationIDParams) ([]InventoryItem, error)
	GetInventoryLevelByID(ctx context.Context, argID id.ID[id.InventoryLevel]) (InventoryLevel, error)
	GetInventoryLevelsByInventoryItemID(ctx context.Context, inventoryItemID id.ID[id.InventoryItem]) ([]InventoryLevel, error)
	GetInventoryLevelsByLocationID(ctx context.Context, locationID id.ID[id.Location]) ([]InventoryLevel, error)
	GetLocationByExternalID(ctx context.Context, arg GetLocationByExternalIDParams) (Location, error)
	GetLocationByID(ctx context.Context, argID id.ID[id.Location]) (Location, error)
	GetLocationsByIntegrationID(ctx context.Context, arg GetLocationsByIntegrationIDParams) ([]Location, error)
	GetOrderByExternalID(ctx context.Context, arg GetOrderByExternalIDParams) (Order, error)
	GetOrderByID(ctx context.Context, argID id.ID[id.Order]) (Order, error)
	GetOrderLineItemByID(ctx context.Context, argID id.ID[id.OrderLineItem]) (OrderLineItem, error)
	GetOrderLineItemsByOrderID(ctx context.Context, orderID id.ID[id.Order]) ([]OrderLineItem, error)
	GetOrdersByIntegrationID(ctx context.Context, arg GetOrdersByIntegrationIDParams) ([]Order, error)
	GetOrdersByIntegrationIDSince(ctx context.Context, arg GetOrdersByIntegrationIDSinceParams) ([]Order, error)
	GetPlatformIntegrationByID(ctx context.Context, argID id.ID[id.PlatformIntegration]) (PlatformIntegration, error)
	GetPlatformIntegrationByShopAndType(ctx context.Context, arg GetPlatformIntegrationByShopAndTypeParams) (PlatformIntegration, error)
	GetPlatformIntegrationsByShopID(ctx context.Context, shopID id.ID[id.ShopifyStore]) ([]PlatformIntegration, error)
	GetProductByExternalID(ctx context.Context, arg GetProductByExternalIDParams) (Product, error)
	GetProductByHandle(ctx context.Context, arg GetProductByHandleParams) (Product, error)
	GetProductByID(ctx context.Context, argID id.ID[id.Product]) (Product, error)
	GetProductVariantByExternalID(ctx context.Context, arg GetProductVariantByExternalIDParams) (ProductVariant, error)
	GetProductVariantByID(ctx context.Context, argID id.ID[id.ProductVariant]) (ProductVariant, error)
	GetProductVariantsByIntegrationID(ctx context.Context, arg GetProductVariantsByIntegrationIDParams) ([]ProductVariant, error)
	GetProductVariantsByProductID(ctx context.Context, productID id.ID[id.Product]) ([]ProductVariant, error)
	GetProductsByIntegrationID(ctx context.Context, arg GetProductsByIntegrationIDParams) ([]Product, error)
	GetSyncState(ctx context.Context, arg GetSyncStateParams) (SyncState, error)
	GetSyncStatesByIntegrationID(ctx context.Context, integrationID id.ID[id.PlatformIntegration]) ([]SyncState, error)
	InsertInventoryItemsBatch(ctx context.Context, arg []InsertInventoryItemsBatchParams) (int64, error)
	InsertLocationsBatch(ctx context.Context, arg []InsertLocationsBatchParams) *InsertLocationsBatchBatchResults
	InsertOrdersBatch(ctx context.Context, arg []InsertOrdersBatchParams) (int64, error)
	InsertProductVariantsBatch(ctx context.Context, arg []InsertProductVariantsBatchParams) *InsertProductVariantsBatchBatchResults
	InsertProductsBatch(ctx context.Context, arg []InsertProductsBatchParams) *InsertProductsBatchBatchResults
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdatePlatformIntegration(ctx context.Context, arg UpdatePlatformIntegrationParams) (PlatformIntegration, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSyncState(ctx context.Context, arg UpdateSyncStateParams) (SyncState, error)
	UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (InventoryItem, error)
	UpsertInventoryLevel(ctx context.Context, arg UpsertInventoryLevelParams) (InventoryLevel, error)
	UpsertLocation(ctx context.Context, arg UpsertLocationParams) (Location, error)
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) (Order, error)
	UpsertOrderLineItem(ctx context.Context, arg UpsertOrderLineItemParams) (OrderLineItem, error)
	UpsertPlatformIntegration(ctx context.Context, arg UpsertPlatformIntegrationParams) (PlatformIntegration, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	UpsertProductVariant(ctx context.Context, arg UpsertProductVariantParams) (ProductVariant, error)
	UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error)
}

var _ Querier = (*Queries)(nil)
