// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"github.com/ConradKurth/forecasting/backend/internal/crypto"
	"github.com/ConradKurth/forecasting/backend/pkg/id"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShopifyStore struct {
	ID          string           `json:"id"`
	UserID      string           `json:"user_id"`
	ShopDomain  string           `json:"shop_domain"`
	AccessToken string           `json:"access_token"`
	Scope       string           `json:"scope"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID          id.ID[id.User]         `json:"id"`
	ShopDomain  string                 `json:"shop_domain"`
	AccessToken crypto.EncryptedSecret `json:"access_token"`
	CreatedAt   pgtype.Timestamp       `json:"created_at"`
	UpdatedAt   pgtype.Timestamp       `json:"updated_at"`
}
