// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"context"

	"github.com/ConradKurth/forecasting/backend/pkg/id"
)

type Querier interface {
	CreateUser(ctx context.Context, argID id.ID[id.User]) (User, error)
	GetUserByID(ctx context.Context, argID id.ID[id.User]) (User, error)
	UpdateUser(ctx context.Context, argID id.ID[id.User]) (User, error)
}

var _ Querier = (*Queries)(nil)
