// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"context"
)

type Querier interface {
	CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByShopDomain(ctx context.Context, shopDomain string) (User, error)
	UpdateUserAccessToken(ctx context.Context, arg UpdateUserAccessTokenParams) (User, error)
}

var _ Querier = (*Queries)(nil)
